### ISSUE TITLE
Nice idea

### ISSUE THREAD

**Issue by pandaro** [tacotexmex/crafting_recipes#1]
Nice idea,
I follow you lately, are you planning something interesting!
And [here](https://github.com/pandaro/goldstandard/blob/master/init.lua)  you can see an old project that will make something of similar than your

**Comment by tacotexmex** [comment]
Yes, I’ve a game in the works. 

That goldstandard mod sounds interesting but I can’t read the code from a glance. Probably my shortcoming. :)

**Comment by pandaro** [comment]
No, it is a very old project, and it contains a lot of comments.
the hypothesis was to create an automatic trading system based 
on the craft recipes,
nodes rarity
tools capability 
and the other things that compose the utility of a node-item-tool.
So if you wont we can arrange a mod together with the goal to have an automatic evaluation of the value of a node-item-tool.

**Comment by tacotexmex** [comment]
That sounds awesome. Let's continue in the forum topic!
